/**
 * Microsoft Edge "Read Aloud" / TTS provider.
 *
 * Uses the public Speech endpoint that the Edge browser exposes for its
 * "Read Aloud" feature. Free for short-to-moderate use. Many high-quality
 * neural voices in dozens of languages.
 *
 * No API key required. Audio bytes go to a Microsoft edge server.
 */
import { registerProvider } from '../registry.js'

const VOICES = [
  // Multilingual neural voices available on Edge Read Aloud
  { value: 'es-ES-ElviraNeural', label: 'Español — Elvira (mujer)' },
  { value: 'es-ES-AlvaroNeural', label: 'Español — Álvaro (hombre)' },
  { value: 'es-MX-DaliaNeural', label: 'Español México — Dalia (mujer)' },
  { value: 'es-MX-JorgeNeural', label: 'Español México — Jorge (hombre)' },
  { value: 'es-AR-ElenaNeural', label: 'Español Argentina — Elena' },
  { value: 'en-US-AriaNeural', label: 'English US — Aria (mujer)' },
  { value: 'en-US-GuyNeural', label: 'English US — Guy (hombre)' },
  { value: 'en-GB-RyanNeural', label: 'English UK — Ryan (hombre)' },
  { value: 'pt-BR-FranciscaNeural', label: 'Português Brasil — Francisca' },
  { value: 'zh-CN-XiaoxiaoNeural', label: '中文 — Xiaoxiao' },
]

const provider = {
  id: 'edge-tts',
  kind: 'tts',
  label: 'Microsoft Edge (online)',
  capabilities: {
    languages: '80+ neural voices',
    requiresKey: false,
    offline: false,
    costPer1kChars: 0,
    privacyNote: 'Audio is generated by Microsoft edge servers.',
  },
  configSchema: [
    { key: 'voice', label: 'Voice', type: 'select', options: VOICES, default: 'es-ES-ElviraNeural' },
    {
      key: 'rate',
      label: 'Speed',
      type: 'select',
      options: [
        { value: '-0.5', label: 'Más lento' },
        { value: '0', label: 'Normal' },
        { value: '0.5', label: 'Más rápido' },
        { value: '1', label: 'Muy rápido' },
      ],
      default: '0',
    },
    {
      key: 'pitch',
      label: 'Pitch',
      type: 'select',
      options: [
        { value: '-50Hz', label: 'Grave' },
        { value: '0Hz', label: 'Normal' },
        { value: '50Hz', label: 'Agudo' },
      ],
      default: '0Hz',
    },
  ],
  defaultConfig: { voice: 'es-ES-ElviraNeural', rate: '0', pitch: '0Hz' },

  async synthesize(text, opts) {
    // SSML for Microsoft TTS endpoint
    const ssml = `
      <speak version="1.0" xmlns="http://www.w3.org/2001/10/synthesis" xml:lang="${opts.voice.split('-').slice(0, 2).join('-')}">
        <voice name="${opts.voice}">
          <prosody rate="${opts.rate || '0'}" pitch="${opts.pitch || '0Hz'}">
            ${escapeXml(text)}
          </prosody>
        </voice>
      </speak>`.trim()

    // Microsoft's TTS endpoint (used by Edge browser for Read Aloud).
    // This is a public endpoint; rate-limited for non-authenticated traffic.
    const endpoint = `https://speech.platform.bing.com/consumer/speech/synthesize/readaloud/edge/v1?trustedclient=true&text=`
    const res = await fetch(endpoint, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/ssml+xml',
        'X-Microsoft-OutputFormat': 'audio-24khz-48kbitrate-mono-mp3',
        'Origin': 'https://www.bing.com',
        'Referer': 'https://www.bing.com/',
      },
      body: ssml,
    })
    if (!res.ok) throw new Error(`Edge TTS ${res.status}`)
    const blob = await res.blob()
    return { kind: 'blob', blob, mimeType: 'audio/mpeg' }
  },
}

function escapeXml(s) {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;')
}

registerProvider(provider)

export default provider