/**
 * Preload bridge — the small surface area exposed to the renderer
 * (UI panel) via Electron's `contextBridge`.
 *
 * The renderer never touches Electron APIs directly.  Instead it talks
 * to `window.abacoBrowser`, which is built here.  All IPC channels go
 * through `ipcRenderer.invoke` so the main process can enforce the
 * agent / manual mode policy before acting.
 *
 * The bridge exposes two views of the same API:
 *
 *   * {@link AbacoBrowserBridge} — the canonical, low-level shape the
 *     renderer actually uses.  This is the surface `ui-panel.tsx`
 *     consumes today (it was defined first; we do not want to break
 *     existing callers).
 *
 *   * {@link BrowserIPC} — the *spec* interface requested by the
 *     task description.  It is a type alias of {@link AbacoBrowserBridge}
 *     with a few convenience entry points (`takeOver`, `startRecording`,
 *     `stopRecording`, `generateSkill`, `saveSkill`) added so the new
 *     `panel.tsx` can use the exact names the spec calls out without
 *     forcing us to fork the bridge.
 *
 * @module desktop/features/browser/preload-bridge
 */

import type { IpcRenderer } from "electron";
import type { GeneratedSkill, RecordingSession } from "./types.js";

/**
 * Subset of a {@link RecordingSession} that flows back to the renderer
 * when a recording stops.  We intentionally do not stream every action
 * across IPC — the renderer only needs enough to show the user *what*
 * was recorded; the full session lives on disk.
 */
export type RecordingResult = Pick<
  RecordingSession,
  "session_id" | "started_at" | "ended_at" | "final_url" | "title" | "actions"
> & {
  /** Total number of captured actions. */
  action_count: number;
  /** Where the raw JSON sidecar was persisted (if `saveRawRecording`
   *  was called). */
  source_path?: string;
};

/**
 * The skill shape the UI panel deals with.  The bridge's `saveSkill`
 * call sends this to the main process, which is responsible for
 * forwarding it to the Python skill store (see `core/skills/...`).
 */
export interface Skill extends GeneratedSkill {
  /** Stable id, generated by the main process.  Optional on the way
   *  in (the main process will fill it in). */
  skill_id?: string;
  /** Recording the skill was generated from (when applicable). */
  source_recording_id?: string;
  /** Model that produced the skill (filled by the generator). */
  generated_by_model?: string;
  /** ISO-8601 timestamp set by the main process on save. */
  created_at?: string;
  /** Version counter; defaults to 1 on save. */
  version?: number;
}

/**
 * The API surface exposed to the renderer.
 *
 * Keep it intentionally small — every method here is a privilege the
 * renderer can ask for.  In particular, `navigate`, `click` and
 * `type` go through the takeover controller in the main process.
 */
export interface AbacoBrowserBridge {
  navigate(url: string): Promise<void>;
  click(selector: string): Promise<void>;
  type(selector: string, text: string): Promise<void>;
  screenshot(): Promise<string>; // base64 data URL
  getCurrentUrl(): Promise<string>;
  getCurrentTitle(): Promise<string>;
  requestTakeover(actor: "agent" | "user"): Promise<void>;
  getMode(): Promise<"agent" | "manual">;
  startRecording(): Promise<string>; // session id
  stopRecording(): Promise<RecordingSummary>;
  saveRawRecording(sessionId: string): Promise<string>; // path
  generateSkill(sessionId: string): Promise<SkillSummary>;
  listSkills(): Promise<SkillSummary[]>;
  listRecordings(): Promise<RecordingSummary[]>;
}

/**
 * The spec interface requested by the task description.
 *
 * It is a *superset* of {@link AbacoBrowserBridge} and reuses the same
 * underlying implementation: the methods that match are aliased; the
 * methods that the spec calls out but the existing bridge does not
 * (`takeOver`, `startRecording(sessionId)`, `stopRecording`,
 * `generateSkill(RecordingResult)`, `saveSkill`) are added as thin
 * conveniences.
 *
 * Concrete classes implementing this bridge should also implement
 * {@link AbacoBrowserBridge} — TypeScript will refuse to compile the
 * object otherwise, which is the point.
 */
export interface BrowserIPC extends AbacoBrowserBridge {
  /** Spec name for {@link AbacoBrowserBridge.navigate}. */
  navigate(url: string): Promise<void>;
  /** Spec name for {@link AbacoBrowserBridge.click}. */
  click(selector: string): Promise<void>;
  /** Spec name for {@link AbacoBrowserBridge.type}. */
  type(selector: string, text: string): Promise<void>;
  /** Spec name for {@link AbacoBrowserBridge.screenshot}.
   *  Returns the raw PNG bytes (the underlying bridge returns a
   *  data-URL string; the wrapper decodes it). */
  screenshot(): Promise<Buffer>;
  /** Start a recording and return the new session id.  Matches
   *  {@link AbacoBrowserBridge.startRecording} exactly; provided here
   *  under the name the spec asks for. */
  startRecording(): Promise<string>;
  /** Stop a recording.  The `sessionId` is currently informational
   *  (the bridge only supports one in-flight recording at a time), but
   *  we accept it so the spec interface stays explicit. */
  stopRecording(sessionId: string): Promise<RecordingResult>;
  /** Switch the takeover controller to the requested mode. */
  takeOver(mode: "agent" | "manual"): Promise<void>;
  /** Generate a skill from a recording.  When `recording` is omitted
   *  the most recent recording on the main process is used. */
  generateSkill(recording?: RecordingResult): Promise<Skill>;
  /** Persist a skill to disk.  Returns `true` on success. */
  saveSkill(skill: Skill): Promise<boolean>;
}

export interface RecordingSummary {
  session_id: string;
  started_at: string;
  ended_at: string;
  final_url: string;
  title: string;
  source_path?: string;
  action_count: number;
}

export interface SkillSummary {
  skill_id: string;
  name: string;
  description: string;
  trigger_patterns: string[];
  version: number;
  created_at: string;
  source_recording_id: string;
  generated_by_model: string;
}

export type BridgeChannel =
  | "abaco:browser:navigate"
  | "abaco:browser:click"
  | "abaco:browser:type"
  | "abaco:browser:screenshot"
  | "abaco:browser:current"
  | "abaco:browser:takeover"
  | "abaco:browser:mode"
  | "abaco:browser:recording:start"
  | "abaco:browser:recording:stop"
  | "abaco:browser:recording:save-raw"
  | "abaco:browser:recording:list"
  | "abaco:browser:skill:generate"
  | "abaco:browser:skill:save"
  | "abaco:browser:skill:list";

/**
 * Build the bridge that will be installed on `window.abacoBrowser`.
 *
 * @param ipc — Electron's `ipcRenderer`, or a fake for tests.
 */
export function buildBridge(ipc: IpcRenderer): AbacoBrowserBridge {
  return {
    navigate: (url) => ipc.invoke("abaco:browser:navigate", { url }),
    click: (selector) => ipc.invoke("abaco:browser:click", { selector }),
    type: (selector, text) =>
      ipc.invoke("abaco:browser:type", { selector, text }),
    screenshot: () => ipc.invoke("abaco:browser:screenshot"),
    getCurrentUrl: () => ipc.invoke("abaco:browser:current", { field: "url" }),
    getCurrentTitle: () =>
      ipc.invoke("abaco:browser:current", { field: "title" }),
    requestTakeover: (actor) =>
      ipc.invoke("abaco:browser:takeover", { actor }),
    getMode: () => ipc.invoke("abaco:browser:mode"),
    startRecording: () => ipc.invoke("abaco:browser:recording:start"),
    stopRecording: () => ipc.invoke("abaco:browser:recording:stop"),
    saveRawRecording: (sessionId) =>
      ipc.invoke("abaco:browser:recording:save-raw", { sessionId }),
    generateSkill: (sessionId) =>
      ipc.invoke("abaco:browser:skill:generate", { sessionId }),
    listSkills: () => ipc.invoke("abaco:browser:skill:list"),
    listRecordings: () => ipc.invoke("abaco:browser:recording:list"),
  };
}

/**
 * Build the full {@link BrowserIPC} surface on top of the low-level
 * bridge.  The result also satisfies {@link AbacoBrowserBridge} so it
 * can be installed in place of `buildBridge` if the host wants the
 * spec interface exposed directly.
 *
 * @param ipc — Electron's `ipcRenderer`, or a fake for tests.
 */
export function buildBrowserIPC(ipc: IpcRenderer): BrowserIPC {
  const base = buildBridge(ipc);
  return {
    ...base,
    async screenshot(): Promise<Buffer> {
      const dataUrl = await base.screenshot();
      return dataUrlToBuffer(dataUrl);
    },
    async stopRecording(_sessionId: string): Promise<RecordingResult> {
      const summary = await base.stopRecording();
      return {
        session_id: summary.session_id,
        started_at: summary.started_at,
        ended_at: summary.ended_at,
        final_url: summary.final_url,
        title: summary.title,
        source_path: summary.source_path,
        action_count: summary.action_count,
        // Actions are not streamed across IPC; the caller should
        // re-load the session from `summary.source_path` if it needs
        // them.  We set the field to an empty array to keep the type
        // shape stable.
        actions: [],
      };
    },
    async takeOver(mode: "agent" | "manual"): Promise<void> {
      await base.requestTakeover(mode === "agent" ? "agent" : "user");
    },
    async generateSkill(recording?: RecordingResult): Promise<Skill> {
      const sessionId = recording?.session_id;
      if (!sessionId) {
        throw new Error(
          "generateSkill requires a recording or session id; the bridge " +
            "currently has no notion of the most recent recording",
        );
      }
      const summary = await base.generateSkill(sessionId);
      return {
        skill_id: summary.skill_id,
        name: summary.name,
        description: summary.description,
        trigger_patterns: summary.trigger_patterns,
        steps: [],
        preconditions: [],
        source_recording_id: summary.source_recording_id,
        generated_by_model: summary.generated_by_model,
        created_at: summary.created_at,
        version: summary.version,
      };
    },
    async saveSkill(skill: Skill): Promise<boolean> {
      // The main process owns the skill store; the renderer only
      // supplies the payload.  We send it through a dedicated channel
      // so the main process can decide how to persist it (Python
      // bridge, JSON file, ...).
      const result = await ipc.invoke("abaco:browser:skill:save", skill);
      return Boolean(result);
    },
  };
}

/**
 * Decode a `data:image/png;base64,...` URL into a raw PNG buffer.  The
 * underlying `screenshot` channel returns a data URL so the renderer
 * can render it directly into an `<img>` without going through Node.
 */
function dataUrlToBuffer(dataUrl: string): Buffer {
  const match = /^data:([^;]+);base64,(.*)$/.exec(dataUrl);
  if (!match) {
    // Already a buffer-like?  Just hand it back.
    return Buffer.from(dataUrl);
  }
  return Buffer.from(match[2] ?? "", "base64");
}

/**
 * The function Electron calls in the preload script.  Returns a
 * strongly-typed object so the renderer can `import { abacoBrowser }`
 * via TypeScript declaration merging.
 */
export function installBridge(
  contextBridge: { exposeInMainWorld: (name: string, api: unknown) => void },
  ipc: IpcRenderer,
): AbacoBrowserBridge {
  const bridge = buildBridge(ipc);
  contextBridge.exposeInMainWorld("abacoBrowser", bridge);
  return bridge;
}

/**
 * Like {@link installBridge} but installs the spec-shaped
 * {@link BrowserIPC} under the same global name.  Hosts that want the
 * full surface (`takeOver`, `saveSkill`, …) should call this instead.
 */
export function installBrowserIPC(
  contextBridge: { exposeInMainWorld: (name: string, api: unknown) => void },
  ipc: IpcRenderer,
): BrowserIPC {
  const ipc_api = buildBrowserIPC(ipc);
  contextBridge.exposeInMainWorld("abacoBrowser", ipc_api);
  return ipc_api;
}
